### ISSUE TITLE
Array element - (dash) syntax support

### ISSUE THREAD

**Issue by MikeRalphson** [jdesrosiers/json-pointer#3]
I can't see any support or tests for the last paragraph of this section of RFC 6901:

> o  If the currently referenced value is a JSON array, the reference
      token MUST contain either:
      *  characters comprised of digits (see ABNF below; note that
           leading zeros are not allowed) that represent an unsigned
           base-10 integer value, making the new referenced value the
           array element with the zero-based index identified by the
           token, or
      *  exactly the single character "-", making the new referenced
           value the (nonexistent) member after the last array element.

Should this be called out in the `README` as unsupported / always throwing an error?

I'm thinking specifically about this paragraph too:

> For example, some applications might stop pointer processing upon an
   error, while others may attempt to recover from missing values by
   inserting default ones.

If you think supporting this is in scope, could you summarise your expectations for `get`, `set` and `assign`, and I could work up a PR?

**Comment by jdesrosiers** [comment]
That was an oversight, it should be supported.

No default values should be inserted. Attempting to access a `-` segment should result in the normal error `Value at '${cursor}' does not have index '${segment}'` except `segment` should be the computed index rather than `-`.

That means
* `-` is only valid as the last element of a pointer.
* `get` should error with the computed index
* `delete` and `unset` should do nothing. Deleting something that doesn't exist is still a no-op, not an error.
* `set` and `assign` should compute the index and assign the value to that index, but it will throw the normal does-not-have-index error if there are segments beyond `-`.

Thanks for finding this and for working on a fix. I'm hopeful that this should just be a fairly small change to the `applySegment` function.

**Comment by jdesrosiers** [comment]
Published as v0.7.0
